# Generated by Django 4.1.7 on 2023-03-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_file_name_alter_file_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
