# Generated by Django 4.2.2 on 2023-08-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='words',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
