# Generated by Django 4.2.2 on 2023-08-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_file_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='words',
            field=models.TextField(blank=True),
        ),
    ]
