# Generated by Django 4.2.2 on 2023-08-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_file_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_words', to='books.file')),
            ],
        ),
        migrations.DeleteModel(
            name='Common_words',
        ),
    ]
